Database Server: database_server::logging::console_logger Class Reference
database_server::logging::console_logger Class Reference
Simple console logger implementing ILogger interface.
#include <console_logger.h>
Public Member Functions
console_logger (kcenon::common::interfaces::log_level min_level=kcenon::common::interfaces::log_level::info)
Construct a console logger with specified minimum level.
~console_logger () override=default
console_logger (const console_logger &)=delete
console_logger & operator= (const console_logger &)=delete
console_logger (console_logger &&)=default
console_logger & operator= (console_logger &&)=default
kcenon::common::VoidResult log (kcenon::common::interfaces::log_level level, const std::string &message) override
Log a message with specified level.
kcenon::common::VoidResult log (kcenon::common::interfaces::log_level level, std::string_view message, const kcenon::common::source_location &loc=kcenon::common::source_location::current()) override
Log a message with source location (C++20)
kcenon::common::VoidResult log (const kcenon::common::interfaces::log_entry &entry) override
Log a structured entry.
bool is_enabled (kcenon::common::interfaces::log_level level) const override
Check if logging is enabled for the specified level.
kcenon::common::VoidResult set_level (kcenon::common::interfaces::log_level level) override
Set the minimum log level.
kcenon::common::interfaces::log_level get_level () const override
Get the current minimum log level.
kcenon::common::VoidResult flush () override
Flush any buffered log messages.
Detailed Description
Simple console logger implementing ILogger interface.
This logger outputs messages to stdout (info and below) or stderr (warning and above). It provides thread-safe logging with configurable log levels and formatted output.
Thread Safety:
All logging methods are thread-safe
Level changes are atomic
Usage:
auto logger = database_server::logging::create_console_logger();
logger->log(kcenon::common::interfaces::log_level::info, "Server started");
Definition at line 79 of file console_logger.h.
Constructor & Destructor Documentation
console_logger() [1/3]
database_server::logging::console_logger::console_logger (kcenon::common::interfaces::log_level min_level = kcenon::common::interfaces::log_level::info) explicit
Construct a console logger with specified minimum level.
Parameters
min_level Minimum log level to output (default: info)
Definition at line 42 of file console_logger.cpp.
~console_logger()
database_server::logging::console_logger::~console_logger () override default
console_logger() [2/3]
database_server::logging::console_logger::console_logger (const console_logger &) delete
console_logger() [3/3]
database_server::logging::console_logger::console_logger (console_logger &&) default
Member Function Documentation
flush()
kcenon::common::VoidResult database_server::logging::console_logger::flush () override
Flush any buffered log messages.
Returns
VoidResult indicating success
Definition at line 106 of file console_logger.cpp.
get_level()
kcenon::common::interfaces::log_level database_server::logging::console_logger::get_level () const override
Get the current minimum log level.
Returns
Current minimum log level
Definition at line 101 of file console_logger.cpp.
is_enabled()
bool database_server::logging::console_logger::is_enabled (kcenon::common::interfaces::log_level level) const override
Check if logging is enabled for the specified level.
Parameters
level Log level to check
Returns
true if logging is enabled for this level
Definition at line 88 of file console_logger.cpp.
Referenced by log(), log(), and log().
log() [1/3]
kcenon::common::VoidResult database_server::logging::console_logger::log (const kcenon::common::interfaces::log_entry & entry) override
Log a structured entry.
Parameters
entry Log entry with all information
Returns
VoidResult indicating success or error
Definition at line 75 of file console_logger.cpp.
References is_enabled().
log() [2/3]
kcenon::common::VoidResult database_server::logging::console_logger::log (kcenon::common::interfaces::log_level level, const std::string & message) override
Log a message with specified level.
Parameters
level Log level
message Log message
Returns
VoidResult indicating success or error
Definition at line 47 of file console_logger.cpp.
References is_enabled().
log() [3/3]
kcenon::common::VoidResult database_server::logging::console_logger::log (kcenon::common::interfaces::log_level level, std::string_view message, const kcenon::common::source_location & loc = kcenon::common::source_location::current()) override
Log a message with source location (C++20)
Parameters
level Log level
message Log message
loc Source location
Returns
VoidResult indicating success or error
Definition at line 60 of file console_logger.cpp.
References is_enabled().
operator=() [1/2]
console_logger & database_server::logging::console_logger::operator= (console_logger &&) default
operator=() [2/2]
console_logger & database_server::logging::console_logger::operator= (const console_logger &) delete
set_level()
kcenon::common::VoidResult database_server::logging::console_logger::set_level (kcenon::common::interfaces::log_level level) override
Set the minimum log level.
Parameters
level Minimum level for messages to be logged
Returns
VoidResult indicating success
Definition at line 94 of file console_logger.cpp.
The documentation for this class was generated from the following files:
include/kcenon/database_server/logging/console_logger.h
src/logging/console_logger.cpp