Database Server: database_server::server_app Class Reference
database_server::server_app Class Reference
Main database server application.
#include <server_app.h>
Public Member Functions
server_app ()
Construct a new server application.
~server_app ()
Destructor - ensures graceful shutdown.
server_app (const server_app &)=delete
server_app & operator= (const server_app &)=delete
server_app (server_app &&)=delete
server_app & operator= (server_app &&)=delete
kcenon::common::VoidResult initialize (const std::string &config_path)
Initialize the server with configuration.
kcenon::common::VoidResult initialize (const server_config &config)
Initialize the server with a configuration object.
int run ()
Run the server main loop.
void stop ()
Request graceful server shutdown.
server_state state () const
Get current server state.
bool is_running () const
Check if server is currently running.
const server_config & config () const
Get the server configuration.
std::shared_ptr< kcenon::common::interfaces::IExecutor > get_executor () const
Get the executor used for background tasks.
void set_executor (std::shared_ptr< kcenon::common::interfaces::IExecutor > executor)
Set the executor for background tasks.
std::shared_ptr< kcenon::common::interfaces::ILogger > get_logger () const
Get the logger used by this server.
void set_logger (std::shared_ptr< kcenon::common::interfaces::ILogger > logger)
Set the logger for this server.
Detailed Description
Main database server application.
This class manages the complete lifecycle of the database gateway server. It handles configuration loading, server initialization, running the main event loop, and graceful shutdown.
Thread Safety:
The start() and stop() methods are thread-safe
State transitions are atomic
Usage Example:
database_server::server_app app;
if (!app.initialize("config.yaml")) {
    return 1;
}
return app.run();
Definition at line 116 of file server_app.h.
Constructor & Destructor Documentation
server_app() [1/3]
database_server::server_app::server_app ()
Construct a new server application.
Definition at line 50 of file server_app.cpp.
~server_app()
database_server::server_app::~server_app ()
Destructor - ensures graceful shutdown.
Definition at line 54 of file server_app.cpp.
References database_server::running, and stop().
server_app() [2/3]
database_server::server_app::server_app (const server_app &) delete
server_app() [3/3]
database_server::server_app::server_app (server_app &&) delete
Member Function Documentation
config()
const server_config & database_server::server_app::config () const
Get the server configuration.
Returns
Reference to the current configuration
Definition at line 352 of file server_app.cpp.
Referenced by initialize().
get_executor()
std::shared_ptr< kcenon::common::interfaces::IExecutor > database_server::server_app::get_executor () const
Get the executor used for background tasks.
Returns
Shared pointer to executor, or nullptr if not set
Definition at line 315 of file server_app.cpp.
get_logger()
std::shared_ptr< kcenon::common::interfaces::ILogger > database_server::server_app::get_logger () const
Get the logger used by this server.
Returns
Shared pointer to logger, or nullptr if not set
Definition at line 332 of file server_app.cpp.
initialize() [1/2]
kcenon::common::VoidResult database_server::server_app::initialize (const server_config & config)
Initialize the server with a configuration object.
Parameters
config Server configuration
Returns
Result indicating success or error with message
Definition at line 85 of file server_app.cpp.
References config(), database_server::logging::create_console_logger(), database_server::initialized, database_server::uninitialized, database_server::server_config::validate(), and database_server::server_config::validation_errors().
initialize() [2/2]
kcenon::common::VoidResult database_server::server_app::initialize (const std::string & config_path)
Initialize the server with configuration.
Parameters
config_path Path to the configuration file (YAML)
Returns
Result indicating success or error with message
This method:
Loads and validates the configuration file
Initializes logging system
Sets up signal handlers
Prepares network listeners (but does not start them)
Definition at line 63 of file server_app.cpp.
References database_server::logging::create_console_logger(), initialize(), and database_server::server_config::load_from_file().
Referenced by initialize(), and main().
is_running()
bool database_server::server_app::is_running () const
Check if server is currently running.
Returns
true if server is in running state
Definition at line 347 of file server_app.cpp.
References database_server::running.
operator=() [1/2]
server_app & database_server::server_app::operator= (const server_app &) delete
operator=() [2/2]
server_app & database_server::server_app::operator= (server_app &&) delete
run()
int database_server::server_app::run ()
Run the server main loop.
Returns
Exit code (0 for success, non-zero for error)
This method blocks until the server is stopped via:
A call to stop()
A SIGTERM or SIGINT signal
Definition at line 211 of file server_app.cpp.
References database_server::initialized, database_server::running, database_server::starting, and database_server::stopped.
Referenced by main().
set_executor()
void database_server::server_app::set_executor (std::shared_ptr< kcenon::common::interfaces::IExecutor > executor)
Set the executor for background tasks.
Parameters
executor Shared pointer to executor
When set, the executor is propagated to query_router and other components that support IExecutor for background task execution.
Definition at line 320 of file server_app.cpp.
set_logger()
void database_server::server_app::set_logger (std::shared_ptr< kcenon::common::interfaces::ILogger > logger)
Set the logger for this server.
Parameters
logger Shared pointer to logger
When set, replaces stdout/stderr logging with structured logging. If not set, a default console logger is created during initialization.
Definition at line 337 of file server_app.cpp.
state()
server_state database_server::server_app::state () const
Get current server state.
Returns
Current server_state
Definition at line 342 of file server_app.cpp.
stop()
void database_server::server_app::stop ()
Request graceful server shutdown.
This method is thread-safe and can be called from any thread or from a signal handler.
Definition at line 260 of file server_app.cpp.
References database_server::running, and database_server::stopping.
Referenced by ~server_app().
The documentation for this class was generated from the following files:
include/kcenon/database_server/server_app.h
src/core/server_app.cpp