Database Server: database_server::resilience::connection_health_monitor Class Reference
database_server::resilience::connection_health_monitor Class Reference
Monitors database connection health with heartbeat.
#include <connection_health_monitor.h>
Public Member Functions
connection_health_monitor (database::core::database_backend *backend, health_check_config config=health_check_config{}, std::shared_ptr< kcenon::common::interfaces::IExecutor > executor=nullptr)
Construct health monitor for database backend.
~connection_health_monitor ()
connection_health_monitor (const connection_health_monitor &)=delete
connection_health_monitor & operator= (const connection_health_monitor &)=delete
connection_health_monitor (connection_health_monitor &&)=delete
connection_health_monitor & operator= (connection_health_monitor &&)=delete
void start_monitoring ()
Start periodic health monitoring Launches background thread for heartbeat checks.
void stop_monitoring ()
Stop health monitoring Stops background thread gracefully.
kcenon::common::Result< health_status > check_now ()
Perform immediate health check.
health_status get_health_status () const
Get current health status (cached)
void record_success (std::chrono::milliseconds query_latency)
Record successful query execution.
void record_failure (const std::string &error_message)
Record failed query execution.
bool is_healthy () const noexcept
Check if connection is currently healthy.
uint32_t get_health_score () const noexcept
Get current health score (0-100)
bool predict_failure () const
Predict if connection is likely to fail soon.
void reset_statistics ()
Reset health statistics Clears all counters and history.
Friends
class health_monitor_job
Detailed Description
Monitors database connection health with heartbeat.
Features:
Periodic heartbeat queries to verify connectivity
Latency tracking with moving average
Health score calculation (0-100)
Predictive failure detection
Query success/failure rate tracking
Health Score Calculation:
40%: Success rate (successful queries / total queries)
30%: Latency performance (faster = higher score)
20%: Consecutive success streak
10%: Connection uptime
Thread Safety:
All public methods are thread-safe
Internal state protected by mutex
Atomic counters for performance metrics
Example Usage:
health_check_config config;
config.heartbeat_interval = std::chrono::seconds(5);
config.failure_threshold = 3;
auto monitor = std::make_unique<connection_health_monitor>(backend, config);
monitor->start_monitoring();
// Later, check health
auto status = monitor->get_health_status();
if (status.health_score < 50) {
    // Consider reconnecting
}
Definition at line 137 of file connection_health_monitor.h.
Constructor & Destructor Documentation
connection_health_monitor() [1/3]
database_server::resilience::connection_health_monitor::connection_health_monitor (database::core::database_backend * backend, health_check_config config = health_check_config{}, std::shared_ptr< kcenon::common::interfaces::IExecutor > executor = nullptr) explicit
Construct health monitor for database backend.
Parameters
backend Database backend to monitor
config Health check configuration
executor Optional executor for background tasks. If null, uses internal thread.
Definition at line 68 of file connection_health_monitor.cpp.
References database_server::resilience::health_status::last_check_time.
~connection_health_monitor()
database_server::resilience::connection_health_monitor::~connection_health_monitor ()
Definition at line 80 of file connection_health_monitor.cpp.
References stop_monitoring().
connection_health_monitor() [2/3]
database_server::resilience::connection_health_monitor::connection_health_monitor (const connection_health_monitor &) delete
connection_health_monitor() [3/3]
database_server::resilience::connection_health_monitor::connection_health_monitor (connection_health_monitor &&) delete
Member Function Documentation
check_now()
kcenon::common::Result< health_status > database_server::resilience::connection_health_monitor::check_now ()
Perform immediate health check.
Returns
Current health status
Definition at line 132 of file connection_health_monitor.cpp.
References database_server::resilience::health_status::failed_queries, database_server::resilience::health_status::health_score, database_server::resilience::health_status::is_healthy, database_server::resilience::health_status::last_check_time, database_server::resilience::health_status::latency, database_server::resilience::health_status::status_message, and database_server::resilience::health_status::successful_queries.
get_health_score()
uint32_t database_server::resilience::connection_health_monitor::get_health_score () const noexcept
Get current health score (0-100)
Returns
Health score
Definition at line 224 of file connection_health_monitor.cpp.
References database_server::resilience::health_status::health_score.
Referenced by is_healthy().
get_health_status()
health_status database_server::resilience::connection_health_monitor::get_health_status () const
Get current health status (cached)
Returns
Latest health status from last check
Definition at line 187 of file connection_health_monitor.cpp.
is_healthy()
bool database_server::resilience::connection_health_monitor::is_healthy () const noexcept
Check if connection is currently healthy.
Returns
true if health score >= min_health_score
Definition at line 218 of file connection_health_monitor.cpp.
References database_server::resilience::health_check_config::failure_threshold, get_health_score(), and database_server::resilience::health_check_config::min_health_score.
operator=() [1/2]
connection_health_monitor & database_server::resilience::connection_health_monitor::operator= (connection_health_monitor &&) delete
operator=() [2/2]
connection_health_monitor & database_server::resilience::connection_health_monitor::operator= (const connection_health_monitor &) delete
predict_failure()
bool database_server::resilience::connection_health_monitor::predict_failure () const
Predict if connection is likely to fail soon.
Returns
true if failure predicted based on trends
Definition at line 230 of file connection_health_monitor.cpp.
References database_server::resilience::health_check_config::failure_threshold, database_server::resilience::health_status::health_score, and database_server::resilience::health_status::latency.
record_failure()
void database_server::resilience::connection_health_monitor::record_failure (const std::string & error_message)
Record failed query execution.
Parameters
error_message Error description
Definition at line 205 of file connection_health_monitor.cpp.
References database_server::resilience::health_check_config::failure_threshold, database_server::resilience::health_status::health_score, database_server::resilience::health_status::is_healthy, and database_server::resilience::health_status::status_message.
record_success()
void database_server::resilience::connection_health_monitor::record_success (std::chrono::milliseconds query_latency)
Record successful query execution.
Parameters
query_latency Query execution time
Definition at line 193 of file connection_health_monitor.cpp.
References database_server::resilience::health_status::health_score.
reset_statistics()
void database_server::resilience::connection_health_monitor::reset_statistics ()
Reset health statistics Clears all counters and history.
Definition at line 265 of file connection_health_monitor.cpp.
References database_server::resilience::health_status::last_check_time.
start_monitoring()
void database_server::resilience::connection_health_monitor::start_monitoring ()
Start periodic health monitoring Launches background thread for heartbeat checks.
Definition at line 85 of file connection_health_monitor.cpp.
stop_monitoring()
void database_server::resilience::connection_health_monitor::stop_monitoring ()
Stop health monitoring Stops background thread gracefully.
Definition at line 111 of file connection_health_monitor.cpp.
Referenced by ~connection_health_monitor().
Friends And Related Symbol Documentation
health_monitor_job
friend class health_monitor_job friend
Definition at line 139 of file connection_health_monitor.h.
The documentation for this class was generated from the following files:
include/kcenon/database_server/resilience/connection_health_monitor.h
src/resilience/connection_health_monitor.cpp