Database Server: database_server::gateway::auth_middleware Class Reference
database_server::gateway::auth_middleware Class Reference
Authentication middleware for gateway server.
#include <auth_middleware.h>
Public Member Functions
auth_middleware (const auth_config &auth_config, const rate_limit_config &rate_config)
Construct auth middleware with default validator.
auth_middleware (const auth_config &auth_config, const rate_limit_config &rate_config, std::shared_ptr< auth_validator > validator)
Construct auth middleware with custom validator.
auth_result authenticate (const std::string &session_id, const auth_token &token)
Authenticate a client request.
bool check_rate_limit (const std::string &client_id)
Check rate limit for client.
auth_result check (const std::string &session_id, const auth_token &token)
Full authentication check including rate limiting.
void on_session_created (const std::string &session_id, const std::string &client_id)
Record session creation event.
void on_session_destroyed (const std::string &session_id)
Record session destruction event.
void set_audit_callback (audit_callback_t callback)
Set audit callback for logging events.
const auth_metrics & metrics () const noexcept
Get authentication metrics.
rate_limiter & get_rate_limiter () noexcept
Get rate limiter.
const auth_config & get_auth_config () const noexcept
Get authentication configuration.
bool is_enabled () const noexcept
Check if authentication is enabled.
Detailed Description
Authentication middleware for gateway server.
Provides authentication, rate limiting, and audit logging for the database gateway. Can be configured with custom token validators.
Thread Safety:
All public methods are thread-safe
Callbacks may be invoked from multiple threads
Usage Example:
auth_config auth_cfg;
auth_cfg.enabled = true;
rate_limit_config rate_cfg;
rate_cfg.requests_per_second = 100;
auto validator = std::make_shared<custom_jwt_validator>();
auth_middleware middleware(auth_cfg, rate_cfg, validator);
middleware.set_audit_callback([](const auth_event& event) {
    logger.info("Auth event: {} for {}", to_string(event.type), event.client_id);
});
auto result = middleware.authenticate(session_id, request.token);
if (!result.success) {
    // Handle authentication failure
}
if (!middleware.check_rate_limit(client_id)) {
    // Handle rate limit exceeded
}
Definition at line 359 of file auth_middleware.h.
Constructor & Destructor Documentation
auth_middleware() [1/2]
database_server::gateway::auth_middleware::auth_middleware (const auth_config & auth_config, const rate_limit_config & rate_config)
Construct auth middleware with default validator.
Parameters
auth_config Authentication configuration
rate_config Rate limit configuration
Definition at line 304 of file auth_middleware.cpp.
auth_middleware() [2/2]
database_server::gateway::auth_middleware::auth_middleware (const auth_config & auth_config, const rate_limit_config & rate_config, std::shared_ptr< auth_validator > validator)
Construct auth middleware with custom validator.
Parameters
auth_config Authentication configuration
rate_config Rate limit configuration
validator Custom token validator
Definition at line 312 of file auth_middleware.cpp.
Member Function Documentation
authenticate()
auth_result database_server::gateway::auth_middleware::authenticate (const std::string & session_id, const auth_token & token)
Authenticate a client request.
Parameters
session_id Session identifier
token Authentication token
Returns
auth_result indicating success or failure
Definition at line 321 of file auth_middleware.cpp.
References database_server::gateway::auth_success, database_server::gateway::auth_result::client_id, database_server::gateway::auth_token::client_id, database_server::gateway::auth_result::code, database_server::gateway::auth_config::enabled, database_server::gateway::auth_metrics::expired_tokens, database_server::gateway::auth_metrics::failed_auths, database_server::gateway::auth_metrics::invalid_tokens, database_server::gateway::auth_token::is_expired(), database_server::gateway::ok, database_server::gateway::auth_result::success, database_server::gateway::auth_metrics::successful_auths, database_server::gateway::token_expired, database_server::gateway::token_invalid, and database_server::gateway::auth_metrics::total_auth_attempts.
Referenced by check().
check()
auth_result database_server::gateway::auth_middleware::check (const std::string & session_id, const auth_token & token)
Full authentication check including rate limiting.
Parameters
session_id Session identifier
token Authentication token
Returns
auth_result with combined status
Definition at line 384 of file auth_middleware.cpp.
References authenticate(), check_rate_limit(), database_server::gateway::auth_token::client_id, database_server::gateway::auth_result::code, database_server::gateway::auth_result::message, database_server::gateway::rate_limited, and database_server::gateway::auth_result::success.
check_rate_limit()
bool database_server::gateway::auth_middleware::check_rate_limit (const std::string & client_id)
Check rate limit for client.
Parameters
client_id Client identifier
Returns
true if request is allowed
Definition at line 370 of file auth_middleware.cpp.
References database_server::gateway::rate_limiter::allow_request(), database_server::gateway::rate_limited, and database_server::gateway::auth_metrics::rate_limited_requests.
Referenced by check().
get_auth_config()
const auth_config & database_server::gateway::auth_middleware::get_auth_config () const noexcept
Get authentication configuration.
Returns
Authentication configuration
Definition at line 444 of file auth_middleware.cpp.
get_rate_limiter()
rate_limiter & database_server::gateway::auth_middleware::get_rate_limiter () noexcept
Get rate limiter.
Returns
Reference to rate limiter
Definition at line 439 of file auth_middleware.cpp.
is_enabled()
bool database_server::gateway::auth_middleware::is_enabled () const noexcept
Check if authentication is enabled.
Returns
true if authentication is enabled
Definition at line 449 of file auth_middleware.cpp.
References database_server::gateway::auth_config::enabled.
metrics()
const auth_metrics & database_server::gateway::auth_middleware::metrics () const noexcept
Get authentication metrics.
Returns
Reference to metrics structure
Definition at line 434 of file auth_middleware.cpp.
on_session_created()
void database_server::gateway::auth_middleware::on_session_created (const std::string & session_id, const std::string & client_id)
Record session creation event.
Parameters
session_id Session identifier
client_id Client identifier
Definition at line 401 of file auth_middleware.cpp.
References database_server::gateway::session_created.
on_session_destroyed()
void database_server::gateway::auth_middleware::on_session_destroyed (const std::string & session_id)
Record session destruction event.
Parameters
session_id Session identifier
Definition at line 412 of file auth_middleware.cpp.
References database_server::gateway::session_destroyed.
set_audit_callback()
void database_server::gateway::auth_middleware::set_audit_callback (audit_callback_t callback)
Set audit callback for logging events.
Parameters
callback Function to call for each auth event
Definition at line 428 of file auth_middleware.cpp.
The documentation for this class was generated from the following files:
include/kcenon/database_server/gateway/auth_middleware.h
src/gateway/auth_middleware.cpp