Database Server: database_server::gateway::gateway_server Class Reference
database_server::gateway::gateway_server Class Reference
TCP server for database gateway.
#include <gateway_server.h>
Public Member Functions
gateway_server (const gateway_config &config)
Constructs a gateway server with configuration.
~gateway_server ()
Destructor - ensures graceful shutdown.
gateway_server (const gateway_server &)=delete
gateway_server & operator= (const gateway_server &)=delete
gateway_server (gateway_server &&)=delete
gateway_server & operator= (gateway_server &&)=delete
kcenon::common::VoidResult start ()
Start the server and begin accepting connections.
kcenon::common::VoidResult stop ()
Stop the server and close all connections.
void wait ()
Wait for the server to stop.
bool is_running () const noexcept
Check if server is running.
void set_request_handler (request_handler_t handler)
Set the request handler.
void set_connection_callback (std::function< void(const client_session &)> callback)
Set connection callback.
void set_disconnection_callback (std::function< void(const std::string &)> callback)
Set disconnection callback.
size_t connection_count () const
Get number of connected clients.
std::optional< client_session > get_session (const std::string &session_id) const
Get session by ID.
bool disconnect_client (const std::string &session_id)
Disconnect a specific client.
const gateway_config & config () const noexcept
Get server configuration.
auth_middleware & get_auth_middleware () noexcept
Get authentication middleware.
const auth_middleware & get_auth_middleware () const noexcept
Get authentication middleware (const)
void set_token_validator (std::shared_ptr< auth_validator > validator)
Set custom token validator.
void set_audit_callback (audit_callback_t callback)
Set audit callback for auth events.
Detailed Description
TCP server for database gateway.
Provides the network interface for the database gateway:
Accepts TCP connections from clients
Handles message serialization/deserialization
Routes requests to appropriate handlers
Manages client sessions
Thread Safety:
All public methods are thread-safe
Callbacks may be invoked from I/O thread
Usage Example:
gateway_config config;
config.port = 5432;
gateway_server server(config);
server.set_request_handler([](const auto& session, const auto& request) {
    // Process request and return response
    return query_response(request.header.message_id);
});
if (auto result = server.start(); !result) {
    std::cerr << "Failed to start: " << result.error().message << "\n";
    return 1;
}
server.wait();
Definition at line 149 of file gateway_server.h.
Constructor & Destructor Documentation
gateway_server() [1/3]
database_server::gateway::gateway_server::gateway_server (const gateway_config & config) explicit
Constructs a gateway server with configuration.
Parameters
config Server configuration
Definition at line 64 of file gateway_server.cpp.
References config(), database_server::gateway::gateway_config::port, and database_server::gateway::gateway_config::server_id.
~gateway_server()
database_server::gateway::gateway_server::~gateway_server ()
Destructor - ensures graceful shutdown.
Definition at line 96 of file gateway_server.cpp.
References stop().
gateway_server() [2/3]
database_server::gateway::gateway_server::gateway_server (const gateway_server &) delete
gateway_server() [3/3]
database_server::gateway::gateway_server::gateway_server (gateway_server &&) delete
Member Function Documentation
config()
const gateway_config & database_server::gateway::gateway_server::config () const noexcept
Get server configuration.
Returns
Current configuration
Definition at line 216 of file gateway_server.cpp.
Referenced by gateway_server().
connection_count()
size_t database_server::gateway::gateway_server::connection_count () const
Get number of connected clients.
Returns
Number of active connections
Definition at line 179 of file gateway_server.cpp.
disconnect_client()
bool database_server::gateway::gateway_server::disconnect_client (const std::string & session_id)
Disconnect a specific client.
Parameters
session_id Session to disconnect
Returns
true if session was found and disconnected
Definition at line 196 of file gateway_server.cpp.
get_auth_middleware() [1/2]
const auth_middleware & database_server::gateway::gateway_server::get_auth_middleware () const noexcept
Get authentication middleware (const)
Returns
Const reference to auth middleware
Definition at line 226 of file gateway_server.cpp.
get_auth_middleware() [2/2]
auth_middleware & database_server::gateway::gateway_server::get_auth_middleware () noexcept
Get authentication middleware.
Returns
Reference to auth middleware
Definition at line 221 of file gateway_server.cpp.
get_session()
std::optional< client_session > database_server::gateway::gateway_server::get_session (const std::string & session_id) const
Get session by ID.
Parameters
session_id Session identifier
Returns
Session if found, nullopt otherwise
Definition at line 185 of file gateway_server.cpp.
is_running()
bool database_server::gateway::gateway_server::is_running () const noexcept
Check if server is running.
Returns
true if server is running
Definition at line 159 of file gateway_server.cpp.
operator=() [1/2]
gateway_server & database_server::gateway::gateway_server::operator= (const gateway_server &) delete
operator=() [2/2]
gateway_server & database_server::gateway::gateway_server::operator= (gateway_server &&) delete
set_audit_callback()
void database_server::gateway::gateway_server::set_audit_callback (audit_callback_t callback)
Set audit callback for auth events.
Parameters
callback Function to call for each auth event
Definition at line 238 of file gateway_server.cpp.
set_connection_callback()
void database_server::gateway::gateway_server::set_connection_callback (std::function< void(const client_session &)> callback)
Set connection callback.
Parameters
callback Called when a client connects
Definition at line 169 of file gateway_server.cpp.
set_disconnection_callback()
void database_server::gateway::gateway_server::set_disconnection_callback (std::function< void(const std::string &)> callback)
Set disconnection callback.
Parameters
callback Called when a client disconnects
Definition at line 174 of file gateway_server.cpp.
set_request_handler()
void database_server::gateway::gateway_server::set_request_handler (request_handler_t handler)
Set the request handler.
Parameters
handler Function to handle incoming requests
Definition at line 164 of file gateway_server.cpp.
set_token_validator()
void database_server::gateway::gateway_server::set_token_validator (std::shared_ptr< auth_validator > validator)
Set custom token validator.
Parameters
validator Custom validator implementation
Definition at line 231 of file gateway_server.cpp.
References database_server::gateway::gateway_config::auth, and database_server::gateway::gateway_config::rate_limit.
start()
kcenon::common::VoidResult database_server::gateway::gateway_server::start ()
Start the server and begin accepting connections.
Returns
Result indicating success or error
Definition at line 104 of file gateway_server.cpp.
References database_server::gateway::gateway_config::port.
stop()
kcenon::common::VoidResult database_server::gateway::gateway_server::stop ()
Stop the server and close all connections.
Returns
Result indicating success or error
Definition at line 125 of file gateway_server.cpp.
Referenced by ~gateway_server().
wait()
void database_server::gateway::gateway_server::wait ()
Wait for the server to stop.
Blocks until stop() is called or the server shuts down.
Definition at line 153 of file gateway_server.cpp.
The documentation for this class was generated from the following files:
include/kcenon/database_server/gateway/gateway_server.h
src/gateway/gateway_server.cpp