Database Server: database_server::gateway::query_router Class Reference
database_server::gateway::query_router Class Reference
Routes and executes queries using connection pool.
#include <query_router.h>
Public Member Functions
query_router (const router_config &config=router_config{})
Constructs a query router with configuration.
~query_router ()=default
Destructor.
query_router (const query_router &)=delete
query_router & operator= (const query_router &)=delete
query_router (query_router &&)=delete
query_router & operator= (query_router &&)=delete
void set_connection_pool (std::shared_ptr< pooling::connection_pool > pool)
Set the connection pool for query execution.
kcenon::common::Result< query_response > execute (const query_request &request)
Execute a query request.
void execute_async (const query_request &request, std::function< void(query_response)> callback)
Execute a query request asynchronously.
const router_metrics & metrics () const noexcept
Get current router metrics.
void reset_metrics ()
Reset metrics counters.
const router_config & config () const noexcept
Get router configuration.
bool is_ready () const noexcept
Check if router is ready for queries.
void set_query_cache (std::shared_ptr< query_cache > cache)
Set query cache for result caching.
std::shared_ptr< query_cache > get_query_cache () const noexcept
Get the current query cache.
void set_executor (std::shared_ptr< kcenon::common::interfaces::IExecutor > executor)
Set executor for async query execution.
std::shared_ptr< kcenon::common::interfaces::IExecutor > get_executor () const noexcept
Get the current executor.
void register_handler (std::unique_ptr< i_query_handler > handler)
Register a custom query handler.
handler_context get_handler_context () const
Get the handler context for query execution.
Static Public Member Functions
static std::unordered_set< std::string > extract_table_names (const std::string &sql, query_type type)
Extract table names from SQL query.
Detailed Description
Routes and executes queries using connection pool.
Provides the core query execution logic for the gateway:
Routes queries to connection pool
Handles different query types (SELECT, INSERT, etc.)
Manages timeouts and retries
Collects execution metrics
Thread Safety:
All public methods are thread-safe
Queries are executed concurrently
Usage Example:
// Create connection pool (from Phase 2)
auto pool = std::make_shared<connection_pool>(...);
pool->initialize();
// Create router
router_config config;
query_router router(config);
router.set_connection_pool(pool);
// Execute query
query_request request("SELECT * FROM users", query_type::select);
auto response = router.execute(request);
Definition at line 146 of file query_router.h.
Constructor & Destructor Documentation
query_router() [1/3]
database_server::gateway::query_router::query_router (const router_config & config = router_config{}) explicit
Constructs a query router with configuration.
Parameters
config Router configuration
Definition at line 62 of file query_router.cpp.
~query_router()
database_server::gateway::query_router::~query_router () default
Destructor.
query_router() [2/3]
database_server::gateway::query_router::query_router (const query_router &) delete
query_router() [3/3]
database_server::gateway::query_router::query_router (query_router &&) delete
Member Function Documentation
config()
const router_config & database_server::gateway::query_router::config () const noexcept
Get router configuration.
Returns
Current configuration
Definition at line 324 of file query_router.cpp.
execute()
kcenon::common::Result< query_response > database_server::gateway::query_router::execute (const query_request & request)
Execute a query request.
Parameters
request The query request to execute
Returns
Result containing query response or error
This is the main entry point for query execution. Handles all query types and returns appropriate response.
Definition at line 160 of file query_router.cpp.
References database_server::gateway::query_response::execution_time_us, database_server::gateway::query_request::header, is_ready(), database_server::gateway::query_response::is_success(), database_server::gateway::router_config::max_concurrent_queries, database_server::gateway::message_header::message_id, database_server::gateway::query_response::status, and database_server::gateway::timeout.
Referenced by database_server::gateway::async_query_job::execute().
execute_async()
void database_server::gateway::query_router::execute_async (const query_request & request, std::function< void(query_response)> callback)
Execute a query request asynchronously.
Parameters
request The query request to execute
callback Callback to invoke with response
The callback is invoked on a worker thread when the query completes.
Definition at line 267 of file query_router.cpp.
References database_server::gateway::error, database_server::gateway::execute, database_server::gateway::query_request::header, and database_server::gateway::message_header::message_id.
extract_table_names()
std::unordered_set< std::string > database_server::gateway::query_router::extract_table_names (const std::string & sql, query_type type) static
Extract table names from SQL query.
Parameters
sql The SQL query string
type The query type
Returns
Set of table names found in the query
Definition at line 361 of file query_router.cpp.
References database_server::gateway::detail::extract_table_names().
get_executor()
std::shared_ptr< kcenon::common::interfaces::IExecutor > database_server::gateway::query_router::get_executor () const noexcept
Get the current executor.
Returns
Shared pointer to executor, or nullptr if not set
Definition at line 354 of file query_router.cpp.
get_handler_context()
handler_context database_server::gateway::query_router::get_handler_context () const
Get the handler context for query execution.
Returns
Handler context with pool and cache references
Definition at line 80 of file query_router.cpp.
References database_server::gateway::handler_context::cache, database_server::gateway::handler_context::default_timeout_ms, database_server::gateway::router_config::default_timeout_ms, and database_server::gateway::handler_context::pool.
get_query_cache()
std::shared_ptr< query_cache > database_server::gateway::query_router::get_query_cache () const noexcept
Get the current query cache.
Returns
Shared pointer to query cache, or nullptr if not set
Definition at line 341 of file query_router.cpp.
is_ready()
bool database_server::gateway::query_router::is_ready () const noexcept
Check if router is ready for queries.
Returns
true if connection pool is set and available
Definition at line 329 of file query_router.cpp.
Referenced by execute().
metrics()
const router_metrics & database_server::gateway::query_router::metrics () const noexcept
Get current router metrics.
Returns
Reference to metrics structure
Definition at line 310 of file query_router.cpp.
operator=() [1/2]
query_router & database_server::gateway::query_router::operator= (const query_router &) delete
operator=() [2/2]
query_router & database_server::gateway::query_router::operator= (query_router &&) delete
register_handler()
void database_server::gateway::query_router::register_handler (std::unique_ptr< i_query_handler > handler)
Register a custom query handler.
Parameters
handler Handler to register
Custom handlers take precedence over built-in handlers. Multiple handlers can be registered for the same query type; the first handler that can_handle() returns true will be used.
Definition at line 74 of file query_router.cpp.
reset_metrics()
void database_server::gateway::query_router::reset_metrics ()
Reset metrics counters.
Definition at line 315 of file query_router.cpp.
References database_server::gateway::router_metrics::failed_queries, database_server::gateway::router_metrics::successful_queries, database_server::gateway::router_metrics::timeout_queries, database_server::gateway::router_metrics::total_execution_time_us, and database_server::gateway::router_metrics::total_queries.
set_connection_pool()
void database_server::gateway::query_router::set_connection_pool (std::shared_ptr< pooling::connection_pool > pool)
Set the connection pool for query execution.
Parameters
pool Shared pointer to connection pool
Definition at line 154 of file query_router.cpp.
set_executor()
void database_server::gateway::query_router::set_executor (std::shared_ptr< kcenon::common::interfaces::IExecutor > executor)
Set executor for async query execution.
Parameters
executor Shared pointer to executor
When set, execute_async will use the executor instead of creating detached threads.
Definition at line 347 of file query_router.cpp.
set_query_cache()
void database_server::gateway::query_router::set_query_cache (std::shared_ptr< query_cache > cache)
Set query cache for result caching.
Parameters
cache Shared pointer to query cache
Definition at line 335 of file query_router.cpp.
The documentation for this class was generated from the following files:
include/kcenon/database_server/gateway/query_router.h
src/gateway/query_router.cpp