Database Server: database_server::gateway::rate_limiter Class Reference
database_server::gateway::rate_limiter Class Reference
Sliding window rate limiter.
#include <auth_middleware.h>
Public Member Functions
rate_limiter (const rate_limit_config &config)
Construct rate limiter with configuration.
bool allow_request (const std::string &client_id)
Check if request is allowed for client.
uint32_t remaining_requests (const std::string &client_id) const
Get remaining requests for client.
bool is_blocked (const std::string &client_id) const
Check if client is currently blocked.
uint64_t block_expires_at (const std::string &client_id) const
Get block expiration time for client.
void reset (const std::string &client_id)
Reset rate limit for client.
void cleanup ()
Clean up expired entries.
const rate_limit_config & config () const noexcept
Get configuration.
Detailed Description
Sliding window rate limiter.
Implements per-client rate limiting using a sliding window algorithm. Supports burst allowance and temporary blocking when limits are exceeded.
Thread Safety:
All public methods are thread-safe
Definition at line 229 of file auth_middleware.h.
Constructor & Destructor Documentation
rate_limiter()
database_server::gateway::rate_limiter::rate_limiter (const rate_limit_config & config) explicit
Construct rate limiter with configuration.
Parameters
config Rate limit configuration
Definition at line 103 of file auth_middleware.cpp.
Member Function Documentation
allow_request()
bool database_server::gateway::rate_limiter::allow_request (const std::string & client_id)
Check if request is allowed for client.
Parameters
client_id Client identifier
Returns
true if request is allowed
Definition at line 108 of file auth_middleware.cpp.
References database_server::gateway::rate_limit_config::block_duration_ms, database_server::gateway::rate_limit_config::burst_size, database_server::gateway::rate_limit_config::enabled, database_server::gateway::rate_limit_config::requests_per_second, and database_server::gateway::rate_limit_config::window_size_ms.
Referenced by database_server::gateway::auth_middleware::check_rate_limit().
block_expires_at()
uint64_t database_server::gateway::rate_limiter::block_expires_at (const std::string & client_id) const
Get block expiration time for client.
Parameters
client_id Client identifier
Returns
Block expiration timestamp (0 if not blocked)
Definition at line 203 of file auth_middleware.cpp.
cleanup()
void database_server::gateway::rate_limiter::cleanup ()
Clean up expired entries.
Definition at line 228 of file auth_middleware.cpp.
References is_blocked(), and database_server::gateway::rate_limit_config::window_size_ms.
config()
const rate_limit_config & database_server::gateway::rate_limiter::config () const noexcept
Get configuration.
Returns
Rate limit configuration
Definition at line 256 of file auth_middleware.cpp.
is_blocked()
bool database_server::gateway::rate_limiter::is_blocked (const std::string & client_id) const
Check if client is currently blocked.
Parameters
client_id Client identifier
Returns
true if client is blocked
Definition at line 185 of file auth_middleware.cpp.
References database_server::gateway::rate_limit_config::enabled.
Referenced by cleanup().
remaining_requests()
uint32_t database_server::gateway::rate_limiter::remaining_requests (const std::string & client_id) const
Get remaining requests for client.
Parameters
client_id Client identifier
Returns
Number of remaining requests in current window
Definition at line 153 of file auth_middleware.cpp.
References database_server::gateway::rate_limit_config::enabled, database_server::gateway::rate_limit_config::requests_per_second, and database_server::gateway::rate_limit_config::window_size_ms.
reset()
void database_server::gateway::rate_limiter::reset (const std::string & client_id)
Reset rate limit for client.
Parameters
client_id Client identifier
Definition at line 222 of file auth_middleware.cpp.
The documentation for this class was generated from the following files:
include/kcenon/database_server/gateway/auth_middleware.h
src/gateway/auth_middleware.cpp