Database Server: database_server::metrics::query_metrics_collector Class Reference
database_server::metrics::query_metrics_collector Class Reference
CRTP-based collector for database query metrics.
#include <query_metrics_collector.h>
Public Member Functions
query_metrics_collector (const collector_options &options=collector_options{})
Constructs a query metrics collector.
~query_metrics_collector ()=default
Destructor.
const query_execution_metrics & query_metrics () const noexcept
Get current query execution metrics.
const cache_performance_metrics & cache_metrics () const noexcept
Get current cache performance metrics.
const pool_performance_metrics & pool_metrics () const noexcept
Get current pool performance metrics.
const session_performance_metrics & session_metrics () const noexcept
Get current session performance metrics.
void reset_metrics ()
Reset all collected metrics.
const collector_options & options () const noexcept
Get collector options.
Public Member Functions inherited from database_server::metrics::query_collector_base< query_metrics_collector >
query_collector_base ()=default
query_collector_base (const query_collector_base &)=delete
query_collector_base (query_collector_base &&)=delete
virtual ~query_collector_base ()=default
query_collector_base & operator= (const query_collector_base &)=delete
query_collector_base & operator= (query_collector_base &&)=delete
bool initialize (const collector_config &config)
Initialize the collector with configuration.
void collect_query_metrics (const query_execution &exec)
Collect query execution metrics.
void collect_pool_metrics (const pool_stats &stats)
Collect connection pool metrics.
void collect_cache_metrics (const cache_stats &stats)
Collect cache metrics.
void collect_session_metrics (const session_stats &stats)
Collect session metrics.
std::string get_name () const
Get the name of this collector.
bool is_healthy () const
Check if the collector is healthy.
stats_map get_statistics () const
Get collector statistics.
bool is_enabled () const noexcept
Check if collector is enabled.
size_t get_collection_count () const noexcept
Get collection count.
size_t get_collection_errors () const noexcept
Get error count.
const query_server_metrics & get_metrics () const noexcept
Get aggregated metrics.
Static Public Attributes
static constexpr const char * collector_name = "query_metrics_collector"
Static collector name for CRTP base.
Protected Member Functions
bool do_initialize (const collector_config &config)
void do_collect_query (const query_execution &exec)
void do_collect_pool (const pool_stats &stats)
void do_collect_cache (const cache_stats &stats)
void do_collect_session (const session_stats &stats)
bool is_available () const
void do_add_statistics (stats_map &stats) const
const query_server_metrics & do_get_metrics () const noexcept
Friends
class query_collector_base< query_metrics_collector >
Additional Inherited Members
Protected Attributes inherited from database_server::metrics::query_collector_base< query_metrics_collector >
bool enabled_
std::mutex stats_mutex_
std::atomic< size_t > collection_count_
std::atomic< size_t > collection_errors_
Detailed Description
CRTP-based collector for database query metrics.
Implements the query_collector_base interface for comprehensive metrics collection. All operations are thread-safe using atomic operations and minimal locking.
Thread Safety:
All collection methods are thread-safe
Statistics retrieval uses shared locks
Metrics storage uses atomic operations
Definition at line 103 of file query_metrics_collector.h.
Constructor & Destructor Documentation
query_metrics_collector()
database_server::metrics::query_metrics_collector::query_metrics_collector (const collector_options & options = collector_options{}) explicit
Constructs a query metrics collector.
Parameters
options Collector configuration options
Definition at line 48 of file query_metrics_collector.cpp.
~query_metrics_collector()
database_server::metrics::query_metrics_collector::~query_metrics_collector () default
Destructor.
Member Function Documentation
cache_metrics()
const cache_performance_metrics & database_server::metrics::query_metrics_collector::cache_metrics () const noexcept
Get current cache performance metrics.
Returns
Reference to cache performance metrics
Definition at line 58 of file query_metrics_collector.cpp.
References database_server::metrics::query_server_metrics::cache_metrics.
do_add_statistics()
void database_server::metrics::query_metrics_collector::do_add_statistics (stats_map & stats) const protected
Definition at line 206 of file query_metrics_collector.cpp.
References database_server::metrics::pool_performance_metrics::active_connections, database_server::metrics::session_performance_metrics::active_sessions, database_server::metrics::pool_performance_metrics::avg_acquisition_time_ms(), database_server::metrics::query_execution_metrics::avg_query_latency_ms(), database_server::metrics::session_performance_metrics::avg_session_duration_sec(), database_server::metrics::cache_performance_metrics::cache_evictions, database_server::metrics::cache_performance_metrics::cache_hit_ratio(), database_server::metrics::cache_performance_metrics::cache_hits, database_server::metrics::query_server_metrics::cache_metrics, database_server::metrics::cache_performance_metrics::cache_misses, database_server::metrics::query_execution_metrics::failed_queries, database_server::metrics::pool_performance_metrics::idle_connections, database_server::metrics::pool_performance_metrics::pool_exhaustion_count, database_server::metrics::query_server_metrics::pool_metrics, database_server::metrics::query_server_metrics::query_metrics, database_server::metrics::query_server_metrics::session_metrics, database_server::metrics::query_execution_metrics::success_rate(), database_server::metrics::query_execution_metrics::successful_queries, database_server::metrics::query_execution_metrics::timeout_queries, database_server::metrics::query_execution_metrics::total_queries, and database_server::metrics::session_performance_metrics::total_sessions.
do_collect_cache()
void database_server::metrics::query_metrics_collector::do_collect_cache (const cache_stats & stats) protected
Definition at line 148 of file query_metrics_collector.cpp.
References database_server::metrics::cache_performance_metrics::cache_entries, database_server::metrics::query_server_metrics::cache_metrics, database_server::metrics::cache_performance_metrics::cache_size_bytes, database_server::metrics::cache_stats::entry_count, database_server::metrics::cache_stats::eviction, database_server::metrics::cache_stats::expiration, database_server::metrics::cache_stats::hit, database_server::metrics::cache_performance_metrics::record_eviction(), database_server::metrics::cache_performance_metrics::record_expiration(), database_server::metrics::cache_performance_metrics::record_hit(), database_server::metrics::cache_performance_metrics::record_miss(), and database_server::metrics::cache_stats::size_bytes.
do_collect_pool()
void database_server::metrics::query_metrics_collector::do_collect_pool (const pool_stats & stats) protected
Definition at line 124 of file query_metrics_collector.cpp.
References database_server::metrics::pool_stats::acquisition_success, database_server::metrics::pool_stats::acquisition_time_ns, database_server::metrics::pool_stats::active_connections, database_server::metrics::pool_performance_metrics::active_connections, database_server::metrics::pool_stats::idle_connections, database_server::metrics::pool_performance_metrics::idle_connections, database_server::metrics::pool_stats::pool_exhausted, database_server::metrics::query_server_metrics::pool_metrics, database_server::metrics::pool_performance_metrics::record_acquisition(), database_server::metrics::pool_performance_metrics::record_exhaustion(), database_server::metrics::pool_stats::total_connections, and database_server::metrics::pool_performance_metrics::total_connections.
do_collect_query()
void database_server::metrics::query_metrics_collector::do_collect_query (const query_execution & exec) protected
Definition at line 112 of file query_metrics_collector.cpp.
References database_server::metrics::query_execution::latency_ns, database_server::metrics::query_server_metrics::query_metrics, database_server::metrics::query_execution::query_type, database_server::metrics::query_execution_metrics::record_query(), database_server::metrics::query_execution::success, database_server::metrics::query_execution::timeout, and database_server::metrics::collector_options::track_query_types.
do_collect_session()
void database_server::metrics::query_metrics_collector::do_collect_session (const session_stats & stats) protected
Definition at line 179 of file query_metrics_collector.cpp.
References database_server::metrics::session_stats::auth_attempted, database_server::metrics::session_stats::auth_success, database_server::metrics::session_stats::duration_ns, database_server::metrics::session_performance_metrics::record_auth(), database_server::metrics::session_performance_metrics::record_session_end(), database_server::metrics::session_performance_metrics::record_session_start(), database_server::metrics::session_stats::session_end, database_server::metrics::query_server_metrics::session_metrics, and database_server::metrics::session_stats::session_start.
do_get_metrics()
const query_server_metrics & database_server::metrics::query_metrics_collector::do_get_metrics () const protected noexcept
Definition at line 248 of file query_metrics_collector.cpp.
do_initialize()
bool database_server::metrics::query_metrics_collector::do_initialize (const collector_config & config) protected
Definition at line 84 of file query_metrics_collector.cpp.
References database_server::metrics::collector_options::histogram_buckets, database_server::metrics::collector_options::track_latency_histogram, and database_server::metrics::collector_options::track_query_types.
is_available()
bool database_server::metrics::query_metrics_collector::is_available () const protected
Definition at line 200 of file query_metrics_collector.cpp.
options()
const collector_options & database_server::metrics::query_metrics_collector::options () const noexcept
Get collector options.
Returns
Current collector options
Definition at line 79 of file query_metrics_collector.cpp.
pool_metrics()
const pool_performance_metrics & database_server::metrics::query_metrics_collector::pool_metrics () const noexcept
Get current pool performance metrics.
Returns
Reference to pool performance metrics
Definition at line 63 of file query_metrics_collector.cpp.
References database_server::metrics::query_server_metrics::pool_metrics.
query_metrics()
const query_execution_metrics & database_server::metrics::query_metrics_collector::query_metrics () const noexcept
Get current query execution metrics.
Returns
Reference to query execution metrics
Definition at line 53 of file query_metrics_collector.cpp.
References database_server::metrics::query_server_metrics::query_metrics.
reset_metrics()
void database_server::metrics::query_metrics_collector::reset_metrics ()
Reset all collected metrics.
Definition at line 73 of file query_metrics_collector.cpp.
References database_server::metrics::query_server_metrics::reset().
session_metrics()
const session_performance_metrics & database_server::metrics::query_metrics_collector::session_metrics () const noexcept
Get current session performance metrics.
Returns
Reference to session performance metrics
Definition at line 68 of file query_metrics_collector.cpp.
References database_server::metrics::query_server_metrics::session_metrics.
Friends And Related Symbol Documentation
query_collector_base< query_metrics_collector >
friend class query_collector_base< query_metrics_collector > friend
Definition at line 87 of file query_metrics_collector.h.
Member Data Documentation
collector_name
constexpr const char* database_server::metrics::query_metrics_collector::collector_name = "query_metrics_collector" static constexpr
Static collector name for CRTP base.
Definition at line 112 of file query_metrics_collector.h.
The documentation for this class was generated from the following files:
include/kcenon/database_server/metrics/query_metrics_collector.h
src/metrics/query_metrics_collector.cpp