Database Server: database_server::resilience::resilient_database_connection Class Reference
database_server::resilience::resilient_database_connection Class Reference
Database connection wrapper with automatic reconnection.
#include <resilient_database_connection.h>
Public Member Functions
resilient_database_connection (std::unique_ptr< database::core::database_backend > backend, reconnection_config config=reconnection_config{}, std::shared_ptr< kcenon::common::interfaces::IExecutor > executor=nullptr)
Construct resilient connection wrapper.
~resilient_database_connection () override
resilient_database_connection (const resilient_database_connection &)=delete
resilient_database_connection & operator= (const resilient_database_connection &)=delete
resilient_database_connection (resilient_database_connection &&)=delete
resilient_database_connection & operator= (resilient_database_connection &&)=delete
database::database_types type () const override
Get database type of underlying backend.
kcenon::common::VoidResult initialize (const database::core::connection_config &config) override
Initialize connection with automatic retry.
kcenon::common::VoidResult shutdown () override
Shutdown connection gracefully.
bool is_initialized () const override
Check if connection is active and healthy.
kcenon::common::Result< uint64_t > insert_query (const std::string &query_string) override
Execute INSERT with automatic reconnection.
kcenon::common::Result< uint64_t > update_query (const std::string &query_string) override
Execute UPDATE with automatic reconnection.
kcenon::common::Result< uint64_t > delete_query (const std::string &query_string) override
Execute DELETE with automatic reconnection.
kcenon::common::Result< database::core::database_result > select_query (const std::string &query_string) override
Execute SELECT with automatic reconnection.
kcenon::common::VoidResult execute_query (const std::string &query_string) override
Execute general query with automatic reconnection.
kcenon::common::VoidResult begin_transaction () override
Begin transaction (requires stable connection)
kcenon::common::VoidResult commit_transaction () override
Commit transaction.
kcenon::common::VoidResult rollback_transaction () override
Rollback transaction.
bool in_transaction () const override
Check if in transaction.
std::string last_error () const override
Get last error message.
std::map< std::string, std::string > connection_info () const override
Get connection information.
kcenon::common::VoidResult ensure_connected ()
Ensure connection is established (with retry)
kcenon::common::Result< health_status > check_health ()
Check connection health status.
void start_auto_recovery ()
Start automatic health monitoring Launches background thread for periodic health checks.
void stop_auto_recovery ()
Stop automatic health monitoring.
connection_state get_state () const noexcept
Get current connection state.
uint32_t get_retry_count () const noexcept
Get number of reconnection attempts since last success.
Detailed Description
Database connection wrapper with automatic reconnection.
Wraps any database_backend implementation and adds:
Automatic reconnection with exponential backoff
Connection health monitoring with heartbeat
Graceful degradation on connection failures
Configurable retry policies
Design Pattern:
Decorator pattern: Wraps database_backend interface
Strategy pattern: Configurable reconnection strategy
Observer pattern: Health status notifications
Thread Safety:
All public methods are thread-safe
Internal state protected by mutex
Atomic state tracking for lock-free reads
Example Usage:
auto backend = backend_registry::create("postgresql", config);
reconnection_config recon_config;
recon_config.initial_delay = std::chrono::milliseconds(100);
recon_config.max_retries = 5;
auto resilient = std::make_shared<resilient_database_connection>(
    std::move(backend), recon_config);
// Automatically reconnects on connection loss
auto result = resilient->select_query("SELECT * FROM users");
Definition at line 147 of file resilient_database_connection.h.
Constructor & Destructor Documentation
resilient_database_connection() [1/3]
database_server::resilience::resilient_database_connection::resilient_database_connection (std::unique_ptr< database::core::database_backend > backend, reconnection_config config = reconnection_config{}, std::shared_ptr< kcenon::common::interfaces::IExecutor > executor = nullptr) explicit
Construct resilient connection wrapper.
Parameters
backend Underlying database backend to wrap
config Reconnection configuration
executor Optional executor for background tasks (health monitoring, etc.)
Definition at line 42 of file resilient_database_connection.cpp.
~resilient_database_connection()
database_server::resilience::resilient_database_connection::~resilient_database_connection () override
Definition at line 57 of file resilient_database_connection.cpp.
References stop_auto_recovery().
resilient_database_connection() [2/3]
database_server::resilience::resilient_database_connection::resilient_database_connection (const resilient_database_connection &) delete
resilient_database_connection() [3/3]
database_server::resilience::resilient_database_connection::resilient_database_connection (resilient_database_connection &&) delete
Member Function Documentation
begin_transaction()
kcenon::common::VoidResult database_server::resilience::resilient_database_connection::begin_transaction () override
Begin transaction (requires stable connection)
Returns
result<void>::ok() on success, error on failure
Definition at line 171 of file resilient_database_connection.cpp.
References ensure_connected().
check_health()
kcenon::common::Result< health_status > database_server::resilience::resilient_database_connection::check_health ()
Check connection health status.
Returns
Health status information
Definition at line 255 of file resilient_database_connection.cpp.
commit_transaction()
kcenon::common::VoidResult database_server::resilience::resilient_database_connection::commit_transaction () override
Commit transaction.
Returns
result<void>::ok() on success, error on failure
Definition at line 183 of file resilient_database_connection.cpp.
connection_info()
std::map< std::string, std::string > database_server::resilience::resilient_database_connection::connection_info () const override
Get connection information.
Returns
Map of connection properties
Definition at line 224 of file resilient_database_connection.cpp.
References database_server::resilience::to_string().
delete_query()
kcenon::common::Result< uint64_t > database_server::resilience::resilient_database_connection::delete_query (const std::string & query_string) override
Execute DELETE with automatic reconnection.
Parameters
query_string SQL DELETE statement
Returns
Number of rows deleted, or error
Definition at line 150 of file resilient_database_connection.cpp.
ensure_connected()
kcenon::common::VoidResult database_server::resilience::resilient_database_connection::ensure_connected ()
Ensure connection is established (with retry)
Returns
result<void>::ok() if connected, error otherwise
Definition at line 245 of file resilient_database_connection.cpp.
References is_initialized().
Referenced by begin_transaction().
execute_query()
kcenon::common::VoidResult database_server::resilience::resilient_database_connection::execute_query (const std::string & query_string) override
Execute general query with automatic reconnection.
Parameters
query_string SQL statement
Returns
result<void>::ok() on success, error on failure
Definition at line 164 of file resilient_database_connection.cpp.
get_retry_count()
uint32_t database_server::resilience::resilient_database_connection::get_retry_count () const noexcept
Get number of reconnection attempts since last success.
Returns
Reconnection attempt count
Definition at line 288 of file resilient_database_connection.cpp.
get_state()
connection_state database_server::resilience::resilient_database_connection::get_state () const noexcept
Get current connection state.
Returns
Current state enum value
Definition at line 283 of file resilient_database_connection.cpp.
in_transaction()
bool database_server::resilience::resilient_database_connection::in_transaction () const override
Check if in transaction.
Returns
true if transaction is active
Definition at line 213 of file resilient_database_connection.cpp.
initialize()
kcenon::common::VoidResult database_server::resilience::resilient_database_connection::initialize (const database::core::connection_config & config) override
Initialize connection with automatic retry.
Parameters
config Connection configuration
Returns
result<void>::ok() on success, error on failure
Definition at line 71 of file resilient_database_connection.cpp.
References database_server::resilience::connected, database_server::resilience::connecting, and database_server::resilience::failed.
insert_query()
kcenon::common::Result< uint64_t > database_server::resilience::resilient_database_connection::insert_query (const std::string & query_string) override
Execute INSERT with automatic reconnection.
Parameters
query_string SQL INSERT statement
Returns
Number of rows inserted, or error
Definition at line 136 of file resilient_database_connection.cpp.
is_initialized()
bool database_server::resilience::resilient_database_connection::is_initialized () const override
Check if connection is active and healthy.
Returns
true if connected and passing health checks
Definition at line 130 of file resilient_database_connection.cpp.
References database_server::resilience::connected.
Referenced by ensure_connected().
last_error()
std::string database_server::resilience::resilient_database_connection::last_error () const override
Get last error message.
Returns
Error message string
Definition at line 218 of file resilient_database_connection.cpp.
operator=() [1/2]
resilient_database_connection & database_server::resilience::resilient_database_connection::operator= (const resilient_database_connection &) delete
operator=() [2/2]
resilient_database_connection & database_server::resilience::resilient_database_connection::operator= (resilient_database_connection &&) delete
rollback_transaction()
kcenon::common::VoidResult database_server::resilience::resilient_database_connection::rollback_transaction () override
Rollback transaction.
Returns
result<void>::ok() on success, error on failure
Definition at line 198 of file resilient_database_connection.cpp.
select_query()
kcenon::common::Result< database::core::database_result > database_server::resilience::resilient_database_connection::select_query (const std::string & query_string) override
Execute SELECT with automatic reconnection.
Parameters
query_string SQL SELECT statement
Returns
Query results, or error
Definition at line 158 of file resilient_database_connection.cpp.
shutdown()
kcenon::common::VoidResult database_server::resilience::resilient_database_connection::shutdown () override
Shutdown connection gracefully.
Returns
result<void>::ok() on success, error on failure
Definition at line 108 of file resilient_database_connection.cpp.
References database_server::resilience::disconnected, and stop_auto_recovery().
start_auto_recovery()
void database_server::resilience::resilient_database_connection::start_auto_recovery ()
Start automatic health monitoring Launches background thread for periodic health checks.
Definition at line 269 of file resilient_database_connection.cpp.
stop_auto_recovery()
void database_server::resilience::resilient_database_connection::stop_auto_recovery ()
Stop automatic health monitoring.
Definition at line 278 of file resilient_database_connection.cpp.
Referenced by shutdown(), and ~resilient_database_connection().
type()
database::database_types database_server::resilience::resilient_database_connection::type () const override
Get database type of underlying backend.
Returns
Database type identifier
Definition at line 66 of file resilient_database_connection.cpp.
update_query()
kcenon::common::Result< uint64_t > database_server::resilience::resilient_database_connection::update_query (const std::string & query_string) override
Execute UPDATE with automatic reconnection.
Parameters
query_string SQL UPDATE statement
Returns
Number of rows updated, or error
Definition at line 143 of file resilient_database_connection.cpp.
The documentation for this class was generated from the following files:
include/kcenon/database_server/resilience/resilient_database_connection.h
src/resilience/resilient_database_connection.cpp