Database Server: database_server::gateway::query_cache Class Reference
database_server::gateway::query_cache Class Reference
Thread-safe LRU cache for query results with TTL support.
#include <query_cache.h>
Public Member Functions
query_cache (const cache_config &config=cache_config{})
Constructs a query cache with configuration.
~query_cache ()=default
Destructor.
query_cache (const query_cache &)=delete
query_cache & operator= (const query_cache &)=delete
query_cache (query_cache &&)=delete
query_cache & operator= (query_cache &&)=delete
kcenon::common::Result< query_response > get (const std::string &cache_key)
Get a cached query response.
kcenon::common::VoidResult put (const std::string &cache_key, const query_response &response, const std::unordered_set< std::string > &table_names={})
Store a query response in the cache.
kcenon::common::VoidResult invalidate (const std::string &table_name)
Invalidate all cache entries for a table.
kcenon::common::VoidResult invalidate_key (const std::string &cache_key)
Invalidate a specific cache entry.
void clear ()
Clear all cached entries.
const cache_metrics & metrics () const noexcept
Get current cache metrics.
void reset_metrics ()
Reset cache metrics.
size_t size () const noexcept
Get current number of cached entries.
bool is_enabled () const noexcept
Check if cache is enabled.
const cache_config & config () const noexcept
Get cache configuration.
Static Public Member Functions
static std::string make_key (const query_request &request)
Generate a cache key from a query request.
Detailed Description
Thread-safe LRU cache for query results with TTL support.
Implements an efficient cache using a combination of:
std::list for O(1) LRU ordering
std::unordered_map for O(1) key lookup
std::shared_mutex for concurrent read access
Thread Safety:
All public methods are thread-safe
Read operations use shared locks for concurrency
Write operations use exclusive locks
Usage Example:
cache_config config;
config.enabled = true;
config.max_entries = 1000;
config.ttl_seconds = 60;
query_cache cache(config);
// Cache a query result
std::string key = query_cache::make_key(request);
cache.put(key, response, {"users"});
// Retrieve from cache
auto cached = cache.get(key);
if (cached) {
    // Use cached response
}
// Invalidate on write
cache.invalidate("users");
Definition at line 159 of file query_cache.h.
Constructor & Destructor Documentation
query_cache() [1/3]
database_server::gateway::query_cache::query_cache (const cache_config & config = cache_config{}) explicit
Constructs a query cache with configuration.
Parameters
config Cache configuration
Definition at line 41 of file query_cache.cpp.
~query_cache()
database_server::gateway::query_cache::~query_cache () default
Destructor.
query_cache() [2/3]
database_server::gateway::query_cache::query_cache (const query_cache &) delete
query_cache() [3/3]
database_server::gateway::query_cache::query_cache (query_cache &&) delete
Member Function Documentation
clear()
void database_server::gateway::query_cache::clear ()
Clear all cached entries.
Definition at line 261 of file query_cache.cpp.
References get().
config()
const cache_config & database_server::gateway::query_cache::config () const noexcept
Get cache configuration.
Returns
Current configuration
Definition at line 291 of file query_cache.cpp.
get()
kcenon::common::Result< query_response > database_server::gateway::query_cache::get (const std::string & cache_key)
Get a cached query response.
Parameters
cache_key The cache key to look up
Returns
Result containing cached response or error
Returns error if:
Cache is disabled (CacheDisabled)
Key not found (CacheMiss)
Entry has expired (CacheExpired)
Definition at line 46 of file query_cache.cpp.
References database_server::gateway::cache_config::enable_lru, database_server::gateway::cache_config::enabled, database_server::gateway::cache_metrics::expirations, get(), database_server::gateway::cache_metrics::hits, and database_server::gateway::cache_metrics::misses.
Referenced by clear(), get(), invalidate(), invalidate_key(), make_key(), put(), and size().
invalidate()
kcenon::common::VoidResult database_server::gateway::query_cache::invalidate (const std::string & table_name)
Invalidate all cache entries for a table.
Parameters
table_name Name of the table to invalidate
Returns
Result indicating success or error
Called when a write operation (INSERT/UPDATE/DELETE) occurs on a table to ensure cached SELECT results are refreshed.
Definition at line 218 of file query_cache.cpp.
References get(), and database_server::gateway::cache_metrics::invalidations.
invalidate_key()
kcenon::common::VoidResult database_server::gateway::query_cache::invalidate_key (const std::string & cache_key)
Invalidate a specific cache entry.
Parameters
cache_key The cache key to invalidate
Returns
Result indicating success or error
Definition at line 247 of file query_cache.cpp.
References get(), and database_server::gateway::cache_metrics::invalidations.
is_enabled()
bool database_server::gateway::query_cache::is_enabled () const noexcept
Check if cache is enabled.
Returns
true if caching is enabled
Definition at line 286 of file query_cache.cpp.
References database_server::gateway::cache_config::enabled.
make_key()
std::string database_server::gateway::query_cache::make_key (const query_request & request) static
Generate a cache key from a query request.
Parameters
request The query request
Returns
Unique cache key based on SQL and parameters
The key is generated by hashing:
SQL query string
Parameter values in order
Query options that affect results
Definition at line 163 of file query_cache.cpp.
References get().
metrics()
const cache_metrics & database_server::gateway::query_cache::metrics () const noexcept
Get current cache metrics.
Returns
Reference to metrics structure
Definition at line 270 of file query_cache.cpp.
operator=() [1/2]
query_cache & database_server::gateway::query_cache::operator= (const query_cache &) delete
operator=() [2/2]
query_cache & database_server::gateway::query_cache::operator= (query_cache &&) delete
put()
kcenon::common::VoidResult database_server::gateway::query_cache::put (const std::string & cache_key, const query_response & response, const std::unordered_set< std::string > & table_names = {})
Store a query response in the cache.
Parameters
cache_key The cache key
response The response to cache
table_names Tables referenced by this query (for invalidation)
Returns
Result indicating success or error
Returns error if:
Cache is disabled (CacheDisabled)
Response size exceeds max_result_size_bytes (CacheEntryTooLarge)
Response indicates an error (CacheInvalidEntry)
Definition at line 91 of file query_cache.cpp.
References database_server::gateway::cache_config::enabled, get(), database_server::gateway::cache_config::max_entries, database_server::gateway::cache_config::max_result_size_bytes, database_server::gateway::ok, database_server::gateway::cache_metrics::puts, database_server::gateway::cache_metrics::skipped_too_large, database_server::gateway::query_response::status, and database_server::gateway::cache_config::ttl_seconds.
reset_metrics()
void database_server::gateway::query_cache::reset_metrics ()
Reset cache metrics.
Definition at line 275 of file query_cache.cpp.
References database_server::gateway::cache_metrics::reset().
size()
size_t database_server::gateway::query_cache::size () const noexcept
Get current number of cached entries.
Returns
Number of entries in cache
Definition at line 280 of file query_cache.cpp.
References get().
The documentation for this class was generated from the following files:
include/kcenon/database_server/gateway/query_cache.h
src/gateway/query_cache.cpp