Database Server: database_server::metrics Namespace Reference
database_server::metrics Namespace Reference
Classes
struct cache_performance_metrics
Metrics for tracking cache performance.
struct cache_stats
Cache statistics snapshot.
struct collector_options
Configuration options for query metrics collector.
struct metrics_utils
Static utility functions for atomic metrics operations.
struct pool_performance_metrics
Metrics for tracking connection pool performance.
struct pool_stats
Connection pool statistics snapshot.
class query_collector_base
CRTP base class for query metrics collectors.
struct query_execution
Information about a single query execution.
struct query_execution_metrics
Metrics for tracking query execution performance.
class query_metrics_collector
CRTP-based collector for database query metrics.
struct query_server_metrics
Aggregated metrics for the entire query server.
struct session_performance_metrics
Metrics for tracking session management.
struct session_stats
Session statistics snapshot.
Concepts
concept QueryCollector
Concept for validating query collector implementations.
Typedefs
using collector_config = std::unordered_map< std::string, std::string >
Type alias for collector configuration map.
using stats_map = std::unordered_map< std::string, double >
Type alias for statistics map.
Functions
query_metrics_collector & get_query_metrics_collector ()
Global query metrics collector instance.
void set_query_metrics_collector (std::shared_ptr< query_metrics_collector > collector)
Set the global query metrics collector instance.
bool initialize_monitoring_integration (const std::string &collector_name)
Initialize monitoring system integration.
void set_metrics_export_callback (std::function< void(const std::vector< monitoring_metric > &)> callback)
Set callback for exporting metrics to monitoring system.
void export_metrics_to_monitoring ()
Export current metrics to monitoring system.
std::unordered_map< std::string, double > get_metrics_for_health_endpoint ()
Get all metrics as a map for health endpoint.
bool is_monitoring_integration_initialized ()
Check if monitoring integration is initialized.
void shutdown_monitoring_integration ()
Shutdown monitoring integration.
Typedef Documentation
collector_config
using database_server::metrics::collector_config = typedef std::unordered_map<std::string, std::string>
Type alias for collector configuration map.
Definition at line 87 of file query_collector_base.h.
stats_map
using database_server::metrics::stats_map = typedef std::unordered_map<std::string, double>
Type alias for statistics map.
Definition at line 92 of file query_collector_base.h.
Function Documentation
export_metrics_to_monitoring()
void database_server::metrics::export_metrics_to_monitoring ()
Export current metrics to monitoring system.
Collects all current metrics from the query_metrics_collector and exports them through the configured callback.
Definition at line 120 of file collector_integration.cpp.
References get_query_metrics_collector().
get_metrics_for_health_endpoint()
std::unordered_map< std::string, double > database_server::metrics::get_metrics_for_health_endpoint ()
Get all metrics as a map for health endpoint.
Returns
Map of metric name to value
Definition at line 316 of file collector_integration.cpp.
References get_query_metrics_collector().
get_query_metrics_collector()
query_metrics_collector & database_server::metrics::get_query_metrics_collector ()
Global query metrics collector instance.
Provides a singleton-like access to the query metrics collector for easy integration throughout the codebase.
Usage:
auto& collector = get_query_metrics_collector();
collector.collect_query_metrics(exec);
Definition at line 282 of file query_metrics_collector.cpp.
Referenced by export_metrics_to_monitoring(), and get_metrics_for_health_endpoint().
initialize_monitoring_integration()
bool database_server::metrics::initialize_monitoring_integration (const std::string & collector_name)
Initialize monitoring system integration.
Parameters
collector_name Name to use for this collector in monitoring system
Returns
true if initialization successful
Definition at line 88 of file collector_integration.cpp.
References collector_name.
is_monitoring_integration_initialized()
bool database_server::metrics::is_monitoring_integration_initialized ()
Check if monitoring integration is initialized.
Returns
true if initialized
Definition at line 326 of file collector_integration.cpp.
set_metrics_export_callback()
void database_server::metrics::set_metrics_export_callback (std::function< void(const std::vector< monitoring_metric > &)> callback)
Set callback for exporting metrics to monitoring system.
Parameters
callback Function to call with collected metrics
Definition at line 107 of file collector_integration.cpp.
set_query_metrics_collector()
void database_server::metrics::set_query_metrics_collector (std::shared_ptr< query_metrics_collector > collector)
Set the global query metrics collector instance.
Parameters
collector Shared pointer to collector instance
Allows injection of a custom collector for testing or advanced configurations.
Definition at line 292 of file query_metrics_collector.cpp.
shutdown_monitoring_integration()
void database_server::metrics::shutdown_monitoring_integration ()
Shutdown monitoring integration.
Definition at line 335 of file collector_integration.cpp.