Database Server: database_server::gateway::detail Namespace Reference
database_server::gateway::detail Namespace Reference
Enumerations
enum class value_type_tag : int {
null_value = 0 , bool_value = 1 , int64_value = 2 , double_value = 3 ,
string_value = 4 , bytes_value = 5
}
Type tags for variant serialization.
Functions
uint64_t current_timestamp_us ()
Get current timestamp in microseconds.
pooling::connection_priority get_priority_for_query_type (query_type type)
Map query type to connection priority.
std::unordered_set< std::string > extract_table_names (const std::string &sql, query_type type)
Extract table names from SQL query.
uint64_t current_timestamp_ms ()
Get current timestamp in milliseconds since Unix epoch.
Enumeration Type Documentation
value_type_tag
enum class database_server::gateway::detail::value_type_tag : int strong
Type tags for variant serialization.
Enumerator
null_value
bool_value
int64_value
double_value
string_value
bytes_value
Definition at line 72 of file serialization_helpers.h.
Function Documentation
current_timestamp_ms()
uint64_t database_server::gateway::detail::current_timestamp_ms () inline
Get current timestamp in milliseconds since Unix epoch.
Definition at line 61 of file serialization_helpers.h.
Referenced by database_server::gateway::auth_token::is_expired(), database_server::gateway::query_response::query_response(), and database_server::gateway::query_response::query_response().
current_timestamp_us()
uint64_t database_server::gateway::detail::current_timestamp_us () inline
Get current timestamp in microseconds.
Definition at line 97 of file query_handlers.h.
extract_table_names()
std::unordered_set< std::string > database_server::gateway::detail::extract_table_names (const std::string & sql, query_type type)
Extract table names from SQL query.
Parameters
sql The SQL query string
type The query type
Returns
Set of table names found in the query
Definition at line 44 of file query_handlers.cpp.
References database_server::gateway::insert, and database_server::gateway::update.
Referenced by database_server::gateway::query_router::extract_table_names().
get_priority_for_query_type()
pooling::connection_priority database_server::gateway::detail::get_priority_for_query_type (query_type type) inline
Map query type to connection priority.
Definition at line 108 of file query_handlers.h.
References database_server::gateway::batch, database_server::gateway::del, database_server::gateway::execute, database_server::gateway::insert, database_server::gateway::ping, database_server::pooling::PRIORITY_HEALTH_CHECK, database_server::pooling::PRIORITY_NORMAL_QUERY, database_server::pooling::PRIORITY_TRANSACTION, database_server::gateway::select, and database_server::gateway::update.