Database Server: database_server::metrics::metrics_utils Struct Reference
database_server::metrics::metrics_utils Struct Reference
Static utility functions for atomic metrics operations.
#include <metrics_base.h>
Static Public Member Functions
static void reset_counter (std::atomic< uint64_t > &counter, std::memory_order order=std::memory_order_relaxed) noexcept
Reset an atomic counter to zero.
static void reset_min (std::atomic< uint64_t > &min_value, std::memory_order order=std::memory_order_relaxed) noexcept
Reset a minimum latency tracker to max value.
static void update_min (std::atomic< uint64_t > &min_value, uint64_t new_value, std::memory_order order=std::memory_order_relaxed) noexcept
Update minimum value using compare-and-swap.
static void update_max (std::atomic< uint64_t > &max_value, uint64_t new_value, std::memory_order order=std::memory_order_relaxed) noexcept
Update maximum value using compare-and-swap.
static void update_min_max (std::atomic< uint64_t > &min_value, std::atomic< uint64_t > &max_value, uint64_t new_value) noexcept
Update both min and max values atomically.
static double average_ns_to_ms (uint64_t total_ns, uint64_t count) noexcept
Calculate average in nanoseconds converted to milliseconds.
static double average_ns_to_sec (uint64_t total_ns, uint64_t count) noexcept
Calculate average in nanoseconds converted to seconds.
static double average_us (uint64_t total_us, uint64_t count) noexcept
Calculate average in microseconds.
static double calculate_rate (uint64_t numerator, uint64_t denominator, double default_value=100.0) noexcept
Calculate percentage rate.
static double calculate_ratio (uint64_t numerator, uint64_t denominator) noexcept
Calculate ratio (not percentage)
Detailed Description
Static utility functions for atomic metrics operations.
Provides common operations used across all metrics structs:
Atomic counter reset
Thread-safe min/max value updates using CAS loops
Average and rate calculations with divide-by-zero protection
Definition at line 85 of file metrics_base.h.
Member Function Documentation
average_ns_to_ms()
static double database_server::metrics::metrics_utils::average_ns_to_ms (uint64_t total_ns, uint64_t count) inline static noexcept
Calculate average in nanoseconds converted to milliseconds.
Parameters
total_ns Total accumulated nanoseconds
count Number of samples
Returns
Average in milliseconds, or 0.0 if count is zero
Definition at line 175 of file metrics_base.h.
Referenced by database_server::metrics::pool_performance_metrics::avg_acquisition_time_ms(), and database_server::metrics::query_execution_metrics::avg_query_latency_ms().
average_ns_to_sec()
static double database_server::metrics::metrics_utils::average_ns_to_sec (uint64_t total_ns, uint64_t count) inline static noexcept
Calculate average in nanoseconds converted to seconds.
Parameters
total_ns Total accumulated nanoseconds
count Number of samples
Returns
Average in seconds, or 0.0 if count is zero
Definition at line 191 of file metrics_base.h.
Referenced by database_server::metrics::session_performance_metrics::avg_session_duration_sec().
average_us()
static double database_server::metrics::metrics_utils::average_us (uint64_t total_us, uint64_t count) inline static noexcept
Calculate average in microseconds.
Parameters
total_us Total accumulated microseconds
count Number of samples
Returns
Average in microseconds, or 0.0 if count is zero
Definition at line 207 of file metrics_base.h.
Referenced by database_server::pooling::priority_metrics< PriorityType >::average_wait_time_for_priority(), and database_server::pooling::pool_metrics::average_wait_time_us().
calculate_rate()
static double database_server::metrics::metrics_utils::calculate_rate (uint64_t numerator, uint64_t denominator, double default_value = 100.0) inline static noexcept
Calculate percentage rate.
Parameters
numerator The count of successful/target items
denominator The total count
default_value Value to return when denominator is zero (default: 100.0)
Returns
Rate as percentage (0.0 - 100.0)
Definition at line 223 of file metrics_base.h.
Referenced by database_server::metrics::cache_performance_metrics::cache_hit_ratio(), database_server::pooling::pool_metrics::success_rate(), and database_server::metrics::query_execution_metrics::success_rate().
calculate_ratio()
static double database_server::metrics::metrics_utils::calculate_ratio (uint64_t numerator, uint64_t denominator) inline static noexcept
Calculate ratio (not percentage)
Parameters
numerator The count of successful/target items
denominator The total count
Returns
Ratio (0.0 - 1.0), or 0.0 if denominator is zero
Definition at line 239 of file metrics_base.h.
reset_counter()
static void database_server::metrics::metrics_utils::reset_counter (std::atomic< uint64_t > & counter, std::memory_order order = std::memory_order_relaxed) inline static noexcept
Reset an atomic counter to zero.
Parameters
counter The atomic counter to reset
order Memory ordering (default: relaxed)
Definition at line 92 of file metrics_base.h.
Referenced by database_server::pooling::pool_metrics::reset(), database_server::metrics::query_execution_metrics::reset(), database_server::metrics::cache_performance_metrics::reset(), database_server::metrics::pool_performance_metrics::reset(), database_server::metrics::session_performance_metrics::reset(), and database_server::pooling::priority_metrics< PriorityType >::reset_all().
reset_min()
static void database_server::metrics::metrics_utils::reset_min (std::atomic< uint64_t > & min_value, std::memory_order order = std::memory_order_relaxed) inline static noexcept
Reset a minimum latency tracker to max value.
Parameters
min_value The atomic minimum value to reset
order Memory ordering (default: relaxed)
Definition at line 103 of file metrics_base.h.
Referenced by database_server::pooling::pool_metrics::reset(), and database_server::metrics::query_execution_metrics::reset().
update_max()
static void database_server::metrics::metrics_utils::update_max (std::atomic< uint64_t > & max_value, uint64_t new_value, std::memory_order order = std::memory_order_relaxed) inline static noexcept
Update maximum value using compare-and-swap.
Thread-safe update that only stores the new value if it's larger than the current maximum.
Parameters
max_value The atomic maximum value to update
new_value The candidate new maximum
order Memory ordering for CAS success (default: relaxed)
Definition at line 140 of file metrics_base.h.
Referenced by database_server::pooling::pool_metrics::update_active(), update_min_max(), and database_server::pooling::pool_metrics::update_queued().
update_min()
static void database_server::metrics::metrics_utils::update_min (std::atomic< uint64_t > & min_value, uint64_t new_value, std::memory_order order = std::memory_order_relaxed) inline static noexcept
Update minimum value using compare-and-swap.
Thread-safe update that only stores the new value if it's smaller than the current minimum.
Parameters
min_value The atomic minimum value to update
new_value The candidate new minimum
order Memory ordering for CAS success (default: relaxed)
Definition at line 119 of file metrics_base.h.
Referenced by update_min_max().
update_min_max()
static void database_server::metrics::metrics_utils::update_min_max (std::atomic< uint64_t > & min_value, std::atomic< uint64_t > & max_value, uint64_t new_value) inline static noexcept
Update both min and max values atomically.
Convenience function that updates both minimum and maximum tracking values with a single new sample.
Parameters
min_value The atomic minimum value to update
max_value The atomic maximum value to update
new_value The new sample value
Definition at line 161 of file metrics_base.h.
References update_max(), and update_min().
Referenced by database_server::pooling::pool_metrics::record_acquisition(), and database_server::metrics::query_execution_metrics::record_query().
The documentation for this struct was generated from the following file:
include/kcenon/database_server/metrics/metrics_base.h