Database Server: database_server::metrics::cache_performance_metrics Struct Reference
database_server::metrics::cache_performance_metrics Struct Reference
Metrics for tracking cache performance.
#include <query_metrics.h>
Public Member Functions
void record_hit ()
Record a cache hit.
void record_miss ()
Record a cache miss.
void record_eviction ()
Record a cache eviction.
void record_expiration ()
Record a cache expiration.
double cache_hit_ratio () const noexcept
Calculate cache hit ratio.
void reset () noexcept
Reset all metrics.
Public Attributes
std::atomic< uint64_t > cache_hits {0}
Cache hit count.
std::atomic< uint64_t > cache_misses {0}
Cache miss count.
std::atomic< uint64_t > cache_evictions {0}
LRU eviction count.
std::atomic< uint64_t > cache_expirations {0}
TTL expiration count.
std::atomic< uint64_t > cache_size_bytes {0}
Current cache size in bytes.
std::atomic< uint64_t > cache_entries {0}
Current number of entries.
Detailed Description
Metrics for tracking cache performance.
Provides atomic counters for cache hit/miss tracking, eviction counts, and memory usage statistics.
Definition at line 182 of file query_metrics.h.
Member Function Documentation
cache_hit_ratio()
double database_server::metrics::cache_performance_metrics::cache_hit_ratio () const inline noexcept
Calculate cache hit ratio.
Returns
Hit ratio as percentage (0.0 - 100.0)
Definition at line 227 of file query_metrics.h.
References cache_hits, cache_misses, and database_server::metrics::metrics_utils::calculate_rate().
Referenced by database_server::metrics::query_metrics_collector::do_add_statistics().
record_eviction()
void database_server::metrics::cache_performance_metrics::record_eviction () inline
Record a cache eviction.
Definition at line 210 of file query_metrics.h.
References cache_evictions.
Referenced by database_server::metrics::query_metrics_collector::do_collect_cache().
record_expiration()
void database_server::metrics::cache_performance_metrics::record_expiration () inline
Record a cache expiration.
Definition at line 218 of file query_metrics.h.
References cache_expirations.
Referenced by database_server::metrics::query_metrics_collector::do_collect_cache().
record_hit()
void database_server::metrics::cache_performance_metrics::record_hit () inline
Record a cache hit.
Definition at line 194 of file query_metrics.h.
References cache_hits.
Referenced by database_server::metrics::query_metrics_collector::do_collect_cache().
record_miss()
void database_server::metrics::cache_performance_metrics::record_miss () inline
Record a cache miss.
Definition at line 202 of file query_metrics.h.
References cache_misses.
Referenced by database_server::metrics::query_metrics_collector::do_collect_cache().
reset()
void database_server::metrics::cache_performance_metrics::reset () inline noexcept
Reset all metrics.
Definition at line 237 of file query_metrics.h.
References cache_evictions, cache_expirations, cache_hits, cache_misses, and database_server::metrics::metrics_utils::reset_counter().
Referenced by database_server::metrics::query_server_metrics::reset().
Member Data Documentation
cache_entries
std::atomic<uint64_t> database_server::metrics::cache_performance_metrics::cache_entries {0}
Current number of entries.
Definition at line 189 of file query_metrics.h.
Referenced by database_server::metrics::query_metrics_collector::do_collect_cache().
cache_evictions
std::atomic<uint64_t> database_server::metrics::cache_performance_metrics::cache_evictions {0}
LRU eviction count.
Definition at line 186 of file query_metrics.h.
Referenced by database_server::metrics::query_metrics_collector::do_add_statistics(), record_eviction(), and reset().
cache_expirations
std::atomic<uint64_t> database_server::metrics::cache_performance_metrics::cache_expirations {0}
TTL expiration count.
Definition at line 187 of file query_metrics.h.
Referenced by record_expiration(), and reset().
cache_hits
std::atomic<uint64_t> database_server::metrics::cache_performance_metrics::cache_hits {0}
Cache hit count.
Definition at line 184 of file query_metrics.h.
Referenced by cache_hit_ratio(), database_server::metrics::query_metrics_collector::do_add_statistics(), record_hit(), and reset().
cache_misses
std::atomic<uint64_t> database_server::metrics::cache_performance_metrics::cache_misses {0}
Cache miss count.
Definition at line 185 of file query_metrics.h.
Referenced by cache_hit_ratio(), database_server::metrics::query_metrics_collector::do_add_statistics(), record_miss(), and reset().
cache_size_bytes
std::atomic<uint64_t> database_server::metrics::cache_performance_metrics::cache_size_bytes {0}
Current cache size in bytes.
Definition at line 188 of file query_metrics.h.
Referenced by database_server::metrics::query_metrics_collector::do_collect_cache().
The documentation for this struct was generated from the following file:
include/kcenon/database_server/metrics/query_metrics.h