Database Server: database_server::server_config Struct Reference
database_server::server_config Struct Reference
Main server configuration.
#include <server_config.h>
Public Member Functions
bool validate () const
Validate the configuration.
std::vector< std::string > validation_errors () const
Get validation error messages.
Static Public Member Functions
static std::optional< server_config > load_from_file (const std::string &path)
Load configuration from a YAML file.
static server_config default_config ()
Create a default configuration.
Public Attributes
std::string name = "database_server"
Server instance name.
network_config network
Network configuration.
logging_config logging
Logging configuration.
pool_config pool
Connection pool configuration.
query_cache_config cache
Query cache configuration.
Detailed Description
Main server configuration.
Contains all configuration for the database server including network settings, logging, and connection pooling.
Definition at line 136 of file server_config.h.
Member Function Documentation
default_config()
server_config database_server::server_config::default_config () static
Create a default configuration.
Returns
Default server configuration
Definition at line 153 of file server_config.cpp.
Referenced by load_from_file(), and main().
load_from_file()
std::optional< server_config > database_server::server_config::load_from_file (const std::string & path) static
Load configuration from a YAML file.
Parameters
path Path to the configuration file
Returns
Loaded configuration, or std::nullopt on error
Definition at line 41 of file server_config.cpp.
References database_server::network_config::cert_file, database_server::network_config::connection_timeout_ms, default_config(), database_server::logging_config::enable_console, database_server::network_config::enable_tls, database_server::pool_config::health_check_interval_ms, database_server::network_config::host, database_server::pool_config::idle_timeout_ms, database_server::network_config::key_file, database_server::logging_config::level, database_server::logging_config::log_file, logging, database_server::network_config::max_connections, database_server::pool_config::max_connections, database_server::pool_config::min_connections, name, network, pool, database_server::network_config::port, and value.
Referenced by database_server::server_app::initialize(), and main().
validate()
bool database_server::server_config::validate () const
Validate the configuration.
Returns
true if configuration is valid
Definition at line 160 of file server_config.cpp.
References validation_errors().
Referenced by database_server::server_app::initialize().
validation_errors()
std::vector< std::string > database_server::server_config::validation_errors () const
Get validation error messages.
Returns
Vector of validation error messages
Definition at line 165 of file server_config.cpp.
References database_server::network_config::cert_file, database_server::network_config::enable_tls, database_server::network_config::host, database_server::network_config::key_file, database_server::logging_config::level, logging, database_server::network_config::max_connections, database_server::pool_config::max_connections, database_server::pool_config::min_connections, name, network, pool, and database_server::network_config::port.
Referenced by database_server::server_app::initialize(), and validate().
Member Data Documentation
cache
query_cache_config database_server::server_config::cache
Query cache configuration.
Definition at line 142 of file server_config.h.
logging
logging_config database_server::server_config::logging
Logging configuration.
Definition at line 140 of file server_config.h.
Referenced by load_from_file(), and validation_errors().
name
std::string database_server::server_config::name = "database_server"
Server instance name.
Definition at line 138 of file server_config.h.
Referenced by load_from_file(), and validation_errors().
network
network_config database_server::server_config::network
Network configuration.
Definition at line 139 of file server_config.h.
Referenced by load_from_file(), and validation_errors().
pool
pool_config database_server::server_config::pool
Connection pool configuration.
Definition at line 141 of file server_config.h.
Referenced by load_from_file(), and validation_errors().
The documentation for this struct was generated from the following files:
include/kcenon/database_server/core/server_config.h
src/core/server_config.cpp